### ISSUE TITLE
Docker Image Build Failure: Seeking Assistance to Resolve the Issue

### ISSUE THREAD

**Issue by donBarbos** [donBarbos/telegram-bot-template#104]
Greetings to the development community! I hope this message finds you well. Unfortunately, I am encountering a persistent problem while attempting to build a Docker image for our project. Despite my efforts and troubleshooting attempts, the image build process fails consistently, impeding further progress.
Check: [Action workflows](https://github.com/donBarbos/telegram-bot-template/actions/workflows/docker-image.yml)
[And how to contribute](https://github.com/donBarbos/telegram-bot-template#-contributing)

**Comment by dearkafka** [comment]
probably, I can help.

see "The usage of the \`get-poetry.py\` script is now deprecated and is replaced by the \`install-poetry.py\` script."

(https://github.com/python-poetry/poetry/blob/c71deb4b75b3672116b3199b2f9ab7e2bf520844/CHANGELOG.md?plain=1#L215)

so that line with poetry install should be updated with latest poetry install

**Comment by donBarbos** [comment]
@dearkafka
thanks, but you can see the `install-poetry` script in my dockerfile:
https://github.com/donBarbos/telegram-bot-template/blob/ddb274756d08c49ec79ace58350b024ebec88a45/Dockerfile?plain=1#L11

**Comment by dearkafka** [comment]
yeah, but later on https://github.com/donBarbos/telegram-bot-template/blob/ddb274756d08c49ec79ace58350b024ebec88a45/Dockerfile?plain=1#L16C1-L17C1

**Comment by donBarbos** [comment]
thx, it helped
